export const HEADER_HEIGHT = 100;

export const INGREDIENT_CATEGORIES = [
  "Herbs and Spices",
  "Condiments and Sauces",
  "Sugars and Sweeteners",
  "Fats and Oils",
  "Dairy and Eggs",
  "Grains and Cereals",
  "Vegetables and Fruits",
  "Proteins",
  "Beverages",
  "Nuts and Seeds",
  "Legumes",
  "Other",
];

export const UNITS = [
  "gram",
  "kilogram",
  "liter",
  "milliliter",
  "meter",
  "centimeter",
  "millimeter",
  "celsius",
  "ounce",
  "pound",
  "teaspoon",
  "tablespoon",
  "cup",
  "pint",
  "quart",
  "gallon",
  "inch",
  "foot",
  "yard",
  "mile",
  "fahrenheit",
];
